spring:
  application:
    name: enterprise-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/shea
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:Santosh@123
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  address: 0.0.0.0
  port: 8080
